name: 'GitHub Actions Send Message Schedule Demo Bot'

on:
  push:
  schedule:
    - cron: '9 * * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with: { ref: main }
      - name: 'Run code Schedule'
        run: bash ./demo.sh
        env:
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}